name: MLSleeping
version: '1.0-SNAPSHOT'
main: org.minelore.mlsleeping.MLSleeping
api-version: '1.21.4'
authors: [ CaHeK2009 ]
description: Plugin that makes voting for the night skip and shows random quote after skip
