name: MLSleeping
version: '0.9.0'
main: org.minelore.mlsleeping.MLSleeping
api-version: '1.21.4'
authors: [ CaHeK2009 ]
description: Plugin that makes voting for the night skip and shows random quote after skip
softdepend: [ GSit ]
commands:
  skipnight:
    description: Voting for a night skip
    usage: /<command> <yes | no>
    permission: skipnight
permissions:
  skipnight:
    description: allows to use plugin command
    default: true
